# Generated by Django 3.2.8 on 2022-07-20 18:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('title', models.CharField(max_length=26)),
                ('location', models.CharField(max_length=26)),
                ('img', models.CharField(max_length=676)),
                ('tickets', models.CharField(max_length=676)),
                ('description', models.CharField(default='', max_length=676)),
                ('end_date', models.DateTimeField()),
                ('start_date', models.DateTimeField()),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
